// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package factory

// Injectors from wire.go:

func InitApp() *App {
	websocketProvider := ProvideWebsocketProvider()
	app := ProvideApp(websocketProvider)
	return app
}
